// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $examples_api_joke from "./routes/examples/api/joke.ts";
import * as $examples_greet_name_ from "./routes/examples/greet/[name].tsx";
import * as $examples_webcomponents_dropdown from "./routes/examples/webcomponents/dropdown.tsx";
import * as $index from "./routes/index.tsx";
import * as $Appbar from "./islands/Appbar.tsx";
import * as $Bottombar from "./islands/Bottombar.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/examples/api/joke.ts": $examples_api_joke,
    "./routes/examples/greet/[name].tsx": $examples_greet_name_,
    "./routes/examples/webcomponents/dropdown.tsx":
      $examples_webcomponents_dropdown,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Appbar.tsx": $Appbar,
    "./islands/Bottombar.tsx": $Bottombar,
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
