// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $app_categories from "./routes/app/categories.tsx";
import * as $app_dashboard from "./routes/app/dashboard.tsx";
import * as $app_packages from "./routes/app/packages.tsx";
import * as $app_prices from "./routes/app/prices.tsx";
import * as $app_users from "./routes/app/users.tsx";
import * as $index from "./routes/index.tsx";
import * as $logout from "./routes/logout.ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/app/categories.tsx": $app_categories,
    "./routes/app/dashboard.tsx": $app_dashboard,
    "./routes/app/packages.tsx": $app_packages,
    "./routes/app/prices.tsx": $app_prices,
    "./routes/app/users.tsx": $app_users,
    "./routes/index.tsx": $index,
    "./routes/logout.ts": $logout,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
