// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $demos_api_joke from "./routes/demos/api/joke.ts";
import * as $demos_dcoms_app_categories from "./routes/demos/dcoms/app/categories.tsx";
import * as $demos_dcoms_app_dashboard from "./routes/demos/dcoms/app/dashboard.tsx";
import * as $demos_dcoms_app_packages from "./routes/demos/dcoms/app/packages.tsx";
import * as $demos_dcoms_app_prices from "./routes/demos/dcoms/app/prices.tsx";
import * as $demos_dcoms_app_users from "./routes/demos/dcoms/app/users.tsx";
import * as $demos_dcoms_index from "./routes/demos/dcoms/index.tsx";
import * as $demos_dcoms_login from "./routes/demos/dcoms/login.tsx";
import * as $demos_dcoms_logout from "./routes/demos/dcoms/logout.ts";
import * as $demos_greet_name_ from "./routes/demos/greet/[name].tsx";
import * as $demos_inmov_layout from "./routes/demos/inmov/_layout.tsx";
import * as $demos_inmov_index from "./routes/demos/inmov/index.tsx";
import * as $demos_saas from "./routes/demos/saas.tsx";
import * as $demos_suntek_layout from "./routes/demos/suntek/_layout.tsx";
import * as $demos_suntek_index from "./routes/demos/suntek/index.tsx";
import * as $demos_threads_layout from "./routes/demos/threads/_layout.tsx";
import * as $demos_threads_index from "./routes/demos/threads/index.tsx";
import * as $demos_vhenz_layout from "./routes/demos/vhenz/_layout.tsx";
import * as $demos_vhenz_index from "./routes/demos/vhenz/index.tsx";
import * as $docs_anchor from "./routes/docs/anchor.tsx";
import * as $index from "./routes/index.tsx";
import * as $shots_layout from "./routes/shots/_layout.tsx";
import * as $shots_index from "./routes/shots/index.tsx";
import * as $tests_1 from "./routes/tests/1.tsx";
import * as $tests_2 from "./routes/tests/2.tsx";
import * as $suntek_Appbar from "./islands/suntek/Appbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/demos/api/joke.ts": $demos_api_joke,
    "./routes/demos/dcoms/app/categories.tsx": $demos_dcoms_app_categories,
    "./routes/demos/dcoms/app/dashboard.tsx": $demos_dcoms_app_dashboard,
    "./routes/demos/dcoms/app/packages.tsx": $demos_dcoms_app_packages,
    "./routes/demos/dcoms/app/prices.tsx": $demos_dcoms_app_prices,
    "./routes/demos/dcoms/app/users.tsx": $demos_dcoms_app_users,
    "./routes/demos/dcoms/index.tsx": $demos_dcoms_index,
    "./routes/demos/dcoms/login.tsx": $demos_dcoms_login,
    "./routes/demos/dcoms/logout.ts": $demos_dcoms_logout,
    "./routes/demos/greet/[name].tsx": $demos_greet_name_,
    "./routes/demos/inmov/_layout.tsx": $demos_inmov_layout,
    "./routes/demos/inmov/index.tsx": $demos_inmov_index,
    "./routes/demos/saas.tsx": $demos_saas,
    "./routes/demos/suntek/_layout.tsx": $demos_suntek_layout,
    "./routes/demos/suntek/index.tsx": $demos_suntek_index,
    "./routes/demos/threads/_layout.tsx": $demos_threads_layout,
    "./routes/demos/threads/index.tsx": $demos_threads_index,
    "./routes/demos/vhenz/_layout.tsx": $demos_vhenz_layout,
    "./routes/demos/vhenz/index.tsx": $demos_vhenz_index,
    "./routes/docs/anchor.tsx": $docs_anchor,
    "./routes/index.tsx": $index,
    "./routes/shots/_layout.tsx": $shots_layout,
    "./routes/shots/index.tsx": $shots_index,
    "./routes/tests/1.tsx": $tests_1,
    "./routes/tests/2.tsx": $tests_2,
  },
  islands: {
    "./islands/suntek/Appbar.tsx": $suntek_Appbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
