// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $codepens_homeExploration from "./routes/codepens/homeExploration.tsx";
import * as $codepens_notionPopOs from "./routes/codepens/notionPopOs.tsx";
import * as $codepens_railFloatingDrawer from "./routes/codepens/railFloatingDrawer.tsx";
import * as $codepens_saasNotification from "./routes/codepens/saasNotification.tsx";
import * as $el_layout from "./routes/el/_layout.tsx";
import * as $el_a from "./routes/el/a.tsx";
import * as $el_article from "./routes/el/article.tsx";
import * as $el_button from "./routes/el/button.tsx";
import * as $el_details from "./routes/el/details.tsx";
import * as $el_dialog from "./routes/el/dialog.tsx";
import * as $el_input_checkbox from "./routes/el/input/checkbox.tsx";
import * as $el_input_color from "./routes/el/input/color.tsx";
import * as $el_input_datalist from "./routes/el/input/datalist.tsx";
import * as $el_input_index from "./routes/el/input/index.tsx";
import * as $el_input_radio from "./routes/el/input/radio.tsx";
import * as $el_input_range from "./routes/el/input/range.tsx";
import * as $el_input_wrapper from "./routes/el/input/wrapper.tsx";
import * as $el_label from "./routes/el/label.tsx";
import * as $el_select from "./routes/el/select.tsx";
import * as $el_table from "./routes/el/table.tsx";
import * as $el_textarea from "./routes/el/textarea.tsx";
import * as $index from "./routes/index.tsx";
import * as $test from "./routes/test.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/codepens/homeExploration.tsx": $codepens_homeExploration,
    "./routes/codepens/notionPopOs.tsx": $codepens_notionPopOs,
    "./routes/codepens/railFloatingDrawer.tsx": $codepens_railFloatingDrawer,
    "./routes/codepens/saasNotification.tsx": $codepens_saasNotification,
    "./routes/el/_layout.tsx": $el_layout,
    "./routes/el/a.tsx": $el_a,
    "./routes/el/article.tsx": $el_article,
    "./routes/el/button.tsx": $el_button,
    "./routes/el/details.tsx": $el_details,
    "./routes/el/dialog.tsx": $el_dialog,
    "./routes/el/input/checkbox.tsx": $el_input_checkbox,
    "./routes/el/input/color.tsx": $el_input_color,
    "./routes/el/input/datalist.tsx": $el_input_datalist,
    "./routes/el/input/index.tsx": $el_input_index,
    "./routes/el/input/radio.tsx": $el_input_radio,
    "./routes/el/input/range.tsx": $el_input_range,
    "./routes/el/input/wrapper.tsx": $el_input_wrapper,
    "./routes/el/label.tsx": $el_label,
    "./routes/el/select.tsx": $el_select,
    "./routes/el/table.tsx": $el_table,
    "./routes/el/textarea.tsx": $el_textarea,
    "./routes/index.tsx": $index,
    "./routes/test.tsx": $test,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
